name: Render QMD Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # This runs the action every day at midnight
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Load and wrangle data
      run: python Main_Stories/stories/example_story/wrangle_data.py
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
    - name: Install Quarto
      run: |
        install.packages('remotes')
        remotes::install_github('quarto-dev/quarto-cli')
    - name: Render QMD files
      run: |
        for file in Main_Stories/stories/*.qmd; do
          Rscript -e "quarto::render('$file')"
        done
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TYLER_PAT }}
        publish_dir: ./_site
